### ISSUE TITLE
Error: Evaluation failed: TypeError: window.loadPreset is not a function

### ISSUE THREAD

**Issue by Catsvilles** [jberg/butterchurn-video-creator#1]
Hi, wanted to try generating a video with butterchurn but unfortunately I'm catching this error when running "generate-screenshots". I'm not sure but Googling shows that maybe something changed in puppeteer a while ago? Any ideas why this may happen?
Am I running the command right (asking because in the example some parameters are wrapped in `[]`)

yarn run generate-screenshots preset_file_path.json data.json preset.json 44100

I'm not sure actually what  [length_in_frames] stands for, but I suppose this is it?

Thank you! :)

**Comment by Catsvilles** [comment]
Okay, using  await page.setContent(`data:text/html;charset=UTF-8,${html}`, {waitUntil: 'networkidle2'}); instead of goto seems to work fine. Rendering time for frames is quite long, took me around 5 min for 19 sec video, this is normal or?

**Comment by jberg** [comment]
Hi @Catsvilles , sorry for the delay and lack of good documentation, glad it seems like you got it to work.

The `[]` arguments are intended to denote optional arguments, but I don't think `audio_analysis_file` is optional, so I sure messed that up 🤐 

`length_in_frames` can be useful if you generate and exceptionally large `audio_analysis_file` and want to make a recording that only uses a subset of frames.

So you can run like:
`yarn run generate-screenshots preset_file_path.json audio_analysis_file 600`

and it should generate 600 screenshots instead of the for the whole audio analysis file.

That seems a bit longer than I would expect for 19 seconds, but depending on the preset and computer hardware it is possible for it to take that long.

**Comment by Catsvilles** [comment]
@jberg thanks for getting back to me! Yeah, since I misunderstood what length_in_frames stands for and used 44100 number for it, I got 562 screenshots for 19 seconds audio, seems a lot, maybe that's why it was so long :)

Anyway, closing this for now, but there are a few more problems with puppeteer at the moment, if/when I will find a solution, will post it here for someone who might stumble across this.
